### ISSUE TITLE
请问cocosCreator是什么版本

### ISSUE THREAD

**Issue by linmengjie** [cyclegtx/cocos2dx-iog-lockstep-sync#1]
怎么把K客户端和服务端跑青睐，可以写个简单的文档吗

**Comment by cyclegtx** [comment]
cocosCreator是2.0.2
https://cowlevel.net/article/2005281
或者
https://indienova.com/u/cyclegtx/blogread/11322
有简单介绍，详细的文档等写完再更新把

**Comment by linmengjie** [comment]
> cocosCreator是2.0.2
> https://cowlevel.net/article/2005281
> 或者
> https://indienova.com/u/cyclegtx/blogread/11322
> 有简单介绍，详细的文档等写完再更新把

看了，也把客户端服务端跑起来了，游戏还是有不同步的情况，应该是物理引擎的一致性问题引擎的，现在是在优化这一块吗，我看资料是说将box2d运算的浮点数运算改成定点数，但是不知道在cccreator里要怎么改

**Comment by cyclegtx** [comment]
改成定点数，然后三角函数之类的用查表应该可以解决问题，但是不是很好修改。最好换一个物理引擎，Photon的TrueSync是可以的，就是没有js的版本，你可以搜一下有没有其他的可以用的引擎。解决不了物理引擎一致性问题，帧同步只能用于不带物理的游戏，回合制游戏之类的。
